server:
  quic_addr: ":8453"          # 修改QUIC端口避免冲突
  http_addr: ":8080"          # HTTP API端口，monitor工具连接这里
  grpc_addr: ":8092"          # 修改为8092避免与business上游服务(8082)冲突
  metrics_addr: ":9090"       # 监控指标端口
  
  # 多上游服务配置 - 测试用
  upstream_services:
    hello:
      - "localhost:8081"      # Hello服务端口
    business:
      - "localhost:8082"      # Business服务端口  
    zone:
      - "localhost:8083"      # Zone服务端口

      
  cert_file: "certs/server.crt"
  key_file: "certs/server.key"
  session_timeout: "5m"
  ack_timeout: "30s"
  max_retries: 3

start_processor:
  enabled: false           # true=异步处理，false=同步处理
  max_workers: 100
  queue_size: 1000
  timeout: "30s"

backup:
  enabled: false

overload_protection:
  enabled: true
  max_connections: 1000
  max_qps: 2000
  qps_window_seconds: 10
  max_upstream_concurrent: 100
  upstream_timeout: "30s"

# 异步处理器配置 - 用于grpc异步调用
async:
  max_workers: 16          # 工作协程数，建议为CPU核数的4倍
  max_queue_size: 10000    # 异步任务队列大小
  task_timeout: "30s"      # 单个异步任务超时时间