server:
  quic_addr: ":8453"          # 修改QUIC端口避免冲突
  http_addr: ":8080"          # HTTP API端口，monitor工具连接这里
  grpc_addr: ":8092"          # 修改为8092避免与business上游服务(8082)冲突
  metrics_addr: ":9090"       # 监控指标端口
  
  # 基于Zone的上游服务配置 - 新版本
  # 上游服务将通过gRPC RegisterUpstream自动注册
  # 无需预配置服务地址，支持动态注册和负载均衡
  
  # Zone路由说明:
  # OpenID 10000-99999 分配到6个zone：
  # Zone 001: 10000-24999 (15000个用户)
  # Zone 002: 25000-39999 (15000个用户) 
  # Zone 003: 40000-54999 (15000个用户)
  # Zone 004: 55000-69999 (15000个用户)
  # Zone 005: 70000-84999 (15000个用户)
  # Zone 006: 85000-99999 (15000个用户)
  
  # 上游服务启动示例命令：
  # ./bin/upstream --zone=001 --addr=localhost:9001 --gateway=localhost:8092
  # ./bin/upstream --zone=002 --addr=localhost:9002 --gateway=localhost:8092
  # ./bin/upstream --zone=003 --addr=localhost:9003 --gateway=localhost:8092
  # ./bin/upstream --zone=004 --addr=localhost:9004 --gateway=localhost:8092
  # ./bin/upstream --zone=005 --addr=localhost:9005 --gateway=localhost:8092
  # ./bin/upstream --zone=006 --addr=localhost:9006 --gateway=localhost:8092
  
  cert_file: "certs/server.crt"
  key_file: "certs/server.key"
  session_timeout: "5m"
  ack_timeout: "30s"
  max_retries: 3

start_processor:
  enabled: false           # true=异步处理，false=同步处理
  max_workers: 100
  queue_size: 1000
  timeout: "30s"

backup:
  enabled: false

overload_protection:
  enabled: true
  max_connections: 1000
  max_qps: 2000
  qps_window_seconds: 10
  max_upstream_concurrent: 100
  upstream_timeout: "30s"

# 异步处理器配置 - 用于grpc异步调用
async:
  max_workers: 16          # 工作协程数，建议为CPU核数的4倍
  max_queue_size: 10000    # 异步任务队列大小
  task_timeout: "30s"      # 单个异步任务超时时间