# gatesvr Docker容器配置文件
# 架构：基于Zone的上游服务自动注册（001-006）
server:
  quic_addr: ":8453"          # QUIC监听地址
  http_addr: ":8080"          # HTTP API地址，monitor工具连接这里  
  grpc_addr: ":8092"          # gRPC服务地址
  metrics_addr: ":9090"       # 监控地址
  
  # 多上游服务配置 - 测试用
  upstream_services:
    hello:
      - "hellosvr:8081"      # Hello服务端口
    business:
      - "businesssvr:8081"      # Business服务端口  
    zone:
      - "zonesvr:8081"      # Zone服务端口
  
  cert_file: "certs/server.crt"
  key_file: "certs/server.key"
  session_timeout: "5m"
  ack_timeout: "30s"
  max_retries: 3

# START消息处理器配置
start_processor:
  enabled: false           # true=异步处理，false=同步处理
  max_workers: 100
  queue_size: 1000
  timeout: "30s"

# 备份配置 - Docker环境暂时禁用
backup:
  enabled: false

# 过载保护配置 - Docker环境优化
overload_protection:
  enabled: true
  max_connections: 10000              # 最大连接数
  connection_warning_threshold: 8000   # 连接预警阈值
  max_qps: 20000                      # 最大QPS
  qps_warning_threshold: 16000        # QPS预警阈值
  qps_window_seconds: 10              # QPS统计窗口
  max_upstream_concurrent: 1000       # 最大上游并发
  upstream_timeout: "30s"             # 上游超时
  upstream_warning_threshold: 800     # 上游并发预警阈值

# 异步处理器配置 - 用于grpc异步调用
async:
  max_workers: 16          # 工作协程数，建议为CPU核数的4倍
  max_queue_size: 10000    # 异步任务队列大小
  task_timeout: "30s"      # 单个异步任务超时时间