// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求类型枚举
type RequestType int32

const (
	RequestType_REQUEST_UNKNOWN   RequestType = 0
	RequestType_REQUEST_START     RequestType = 1 // (新增) 连接建立请求
	RequestType_REQUEST_STOP      RequestType = 2 // (新增) 连接断开请求
	RequestType_REQUEST_HEARTBEAT RequestType = 3 // 心跳请求
	RequestType_REQUEST_BUSINESS  RequestType = 4 // 业务请求
	RequestType_REQUEST_ACK       RequestType = 5 // ACK确认
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "REQUEST_UNKNOWN",
		1: "REQUEST_START",
		2: "REQUEST_STOP",
		3: "REQUEST_HEARTBEAT",
		4: "REQUEST_BUSINESS",
		5: "REQUEST_ACK",
	}
	RequestType_value = map[string]int32{
		"REQUEST_UNKNOWN":   0,
		"REQUEST_START":     1,
		"REQUEST_STOP":      2,
		"REQUEST_HEARTBEAT": 3,
		"REQUEST_BUSINESS":  4,
		"REQUEST_ACK":       5,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

// 推送类型枚举
type PushType int32

const (
	PushType_PUSH_UNKNOWN        PushType = 0
	PushType_PUSH_START_RESP     PushType = 1 // (新增) 连接建立的响应
	PushType_PUSH_HEARTBEAT_RESP PushType = 2 // 心跳响应
	PushType_PUSH_BUSINESS_DATA  PushType = 3 // 业务数据推送
	PushType_PUSH_ERROR          PushType = 4 // 错误推送
)

// Enum value maps for PushType.
var (
	PushType_name = map[int32]string{
		0: "PUSH_UNKNOWN",
		1: "PUSH_START_RESP",
		2: "PUSH_HEARTBEAT_RESP",
		3: "PUSH_BUSINESS_DATA",
		4: "PUSH_ERROR",
	}
	PushType_value = map[string]int32{
		"PUSH_UNKNOWN":        0,
		"PUSH_START_RESP":     1,
		"PUSH_HEARTBEAT_RESP": 2,
		"PUSH_BUSINESS_DATA":  3,
		"PUSH_ERROR":          4,
	}
)

func (x PushType) Enum() *PushType {
	p := new(PushType)
	*p = x
	return p
}

func (x PushType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[1].Descriptor()
}

func (PushType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[1]
}

func (x PushType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushType.Descriptor instead.
func (PushType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

// 断开原因
type StopRequest_Reason int32

const (
	StopRequest_UNKNOWN        StopRequest_Reason = 0
	StopRequest_USER_LOGOUT    StopRequest_Reason = 1 // 用户主动登出
	StopRequest_APP_CLOSE      StopRequest_Reason = 2 // 应用关闭
	StopRequest_SWITCH_ACCOUNT StopRequest_Reason = 3 // 切换账号
)

// Enum value maps for StopRequest_Reason.
var (
	StopRequest_Reason_name = map[int32]string{
		0: "UNKNOWN",
		1: "USER_LOGOUT",
		2: "APP_CLOSE",
		3: "SWITCH_ACCOUNT",
	}
	StopRequest_Reason_value = map[string]int32{
		"UNKNOWN":        0,
		"USER_LOGOUT":    1,
		"APP_CLOSE":      2,
		"SWITCH_ACCOUNT": 3,
	}
)

func (x StopRequest_Reason) Enum() *StopRequest_Reason {
	p := new(StopRequest_Reason)
	*p = x
	return p
}

func (x StopRequest_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StopRequest_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[2].Descriptor()
}

func (StopRequest_Reason) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[2]
}

func (x StopRequest_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StopRequest_Reason.Descriptor instead.
func (StopRequest_Reason) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4, 0}
}

// 客户端请求消息 (通用信封)
type ClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         uint32                 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                                                                 // 消息ID
	SeqId         uint64                 `protobuf:"varint,2,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`                                                                 // 序列号，用于可靠性保证
	Type          RequestType            `protobuf:"varint,3,opt,name=type,proto3,enum=gatesvr.proto.RequestType" json:"type,omitempty"`                                                 // 请求类型
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                                                           // 消息载荷, 根据type类型解析为不同的消息体
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展头部
	Openid        string                 `protobuf:"bytes,6,opt,name=openid,proto3" json:"openid,omitempty"`                                                                             // 客户端唯一身份标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *ClientRequest) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *ClientRequest) GetSeqId() uint64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *ClientRequest) GetType() RequestType {
	if x != nil {
		return x.Type
	}
	return RequestType_REQUEST_UNKNOWN
}

func (x *ClientRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ClientRequest) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

// 服务端推送消息 (通用信封)
type ServerPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         uint32                 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                                                                 // 消息ID
	SeqId         uint64                 `protobuf:"varint,2,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`                                                                 // 序列号
	Type          PushType               `protobuf:"varint,3,opt,name=type,proto3,enum=gatesvr.proto.PushType" json:"type,omitempty"`                                                    // 推送类型
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                                                           // 消息载荷, 根据type类型解析为不同的消息体
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展头部
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPush) Reset() {
	*x = ServerPush{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPush) ProtoMessage() {}

func (x *ServerPush) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPush.ProtoReflect.Descriptor instead.
func (*ServerPush) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *ServerPush) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *ServerPush) GetSeqId() uint64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *ServerPush) GetType() PushType {
	if x != nil {
		return x.Type
	}
	return PushType_PUSH_UNKNOWN
}

func (x *ServerPush) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerPush) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// (新增) 连接建立请求 (startmsg)
// 当客户端与gatesvr建立TCP连接后，应立即发送的第一个应用层消息
type StartRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Openid         string                 `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`                                            // (新增) 客户端的用户唯一标识 (User ID)
	ClientId       string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                        // 客户端实例的唯一标识 (例如设备ID, Device ID)
	AuthToken      string                 `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`                     // 用于认证的令牌
	LastAckedSeqId uint64                 `protobuf:"varint,4,opt,name=last_acked_seq_id,json=lastAckedSeqId,proto3" json:"last_acked_seq_id,omitempty"` // 上次成功确认的消息序列号, 用于重连时消息同步
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *StartRequest) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *StartRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *StartRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *StartRequest) GetLastAckedSeqId() uint64 {
	if x != nil {
		return x.LastAckedSeqId
	}
	return 0
}

// (新增) 连接建立响应
// 服务器对 StartRequest 的响应
type StartResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                              // 是否成功
	Error             *ErrorMessage          `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                                   // 如果失败，返回错误信息
	HeartbeatInterval int32                  `protobuf:"varint,3,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"` // (可选) 服务器建议的心跳间隔（秒）
	ConnectionId      string                 `protobuf:"bytes,4,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`                 // 本次连接在服务器端的唯一ID，用于日志追踪
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *StartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartResponse) GetError() *ErrorMessage {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *StartResponse) GetHeartbeatInterval() int32 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

func (x *StartResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

// 客户端在主动关闭连接前，应尽力发送此消息
type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        StopRequest_Reason     `protobuf:"varint,1,opt,name=reason,proto3,enum=gatesvr.proto.StopRequest_Reason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *StopRequest) GetReason() StopRequest_Reason {
	if x != nil {
		return x.Reason
	}
	return StopRequest_UNKNOWN
}

// 心跳请求载荷
type HeartbeatRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientTimestamp int64                  `protobuf:"varint,1,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"` // 客户端发送时的时间戳
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatRequest) GetClientTimestamp() int64 {
	if x != nil {
		return x.ClientTimestamp
	}
	return 0
}

// 心跳响应载荷
type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientTimestamp int64                  `protobuf:"varint,1,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"` // 从客户端请求中带回的时间戳
	ServerTimestamp int64                  `protobuf:"varint,2,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"` // 服务器接收到请求时的时间戳
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetClientTimestamp() int64 {
	if x != nil {
		return x.ClientTimestamp
	}
	return 0
}

func (x *HeartbeatResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

// 业务请求载荷（示例）
type BusinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Params        map[string]string      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessRequest) Reset() {
	*x = BusinessRequest{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessRequest) ProtoMessage() {}

func (x *BusinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessRequest.ProtoReflect.Descriptor instead.
func (*BusinessRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *BusinessRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *BusinessRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *BusinessRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 业务响应载荷（示例）
type BusinessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessResponse) Reset() {
	*x = BusinessResponse{}
	mi := &file_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessResponse) ProtoMessage() {}

func (x *BusinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessResponse.ProtoReflect.Descriptor instead.
func (*BusinessResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *BusinessResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BusinessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BusinessResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 错误消息载荷
type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{9}
}

func (x *ErrorMessage) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ErrorMessage) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ErrorMessage) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// 客户端ACK消息
type ClientAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AckedSeqId    uint64                 `protobuf:"varint,1,opt,name=acked_seq_id,json=ackedSeqId,proto3" json:"acked_seq_id,omitempty"` // 已确认的序列号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAck) Reset() {
	*x = ClientAck{}
	mi := &file_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAck) ProtoMessage() {}

func (x *ClientAck) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAck.ProtoReflect.Descriptor instead.
func (*ClientAck) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{10}
}

func (x *ClientAck) GetAckedSeqId() uint64 {
	if x != nil {
		return x.AckedSeqId
	}
	return 0
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\rgatesvr.proto\"\xa0\x02\n" +
	"\rClientRequest\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\rR\x05msgId\x12\x15\n" +
	"\x06seq_id\x18\x02 \x01(\x04R\x05seqId\x12.\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1a.gatesvr.proto.RequestTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12C\n" +
	"\aheaders\x18\x05 \x03(\v2).gatesvr.proto.ClientRequest.HeadersEntryR\aheaders\x12\x16\n" +
	"\x06openid\x18\x06 \x01(\tR\x06openid\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xff\x01\n" +
	"\n" +
	"ServerPush\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\rR\x05msgId\x12\x15\n" +
	"\x06seq_id\x18\x02 \x01(\x04R\x05seqId\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x17.gatesvr.proto.PushTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12@\n" +
	"\aheaders\x18\x05 \x03(\v2&.gatesvr.proto.ServerPush.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x01\n" +
	"\fStartRequest\x12\x16\n" +
	"\x06openid\x18\x01 \x01(\tR\x06openid\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\tR\tauthToken\x12)\n" +
	"\x11last_acked_seq_id\x18\x04 \x01(\x04R\x0elastAckedSeqId\"\xb0\x01\n" +
	"\rStartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x121\n" +
	"\x05error\x18\x02 \x01(\v2\x1b.gatesvr.proto.ErrorMessageR\x05error\x12-\n" +
	"\x12heartbeat_interval\x18\x03 \x01(\x05R\x11heartbeatInterval\x12#\n" +
	"\rconnection_id\x18\x04 \x01(\tR\fconnectionId\"\x93\x01\n" +
	"\vStopRequest\x129\n" +
	"\x06reason\x18\x01 \x01(\x0e2!.gatesvr.proto.StopRequest.ReasonR\x06reason\"I\n" +
	"\x06Reason\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0f\n" +
	"\vUSER_LOGOUT\x10\x01\x12\r\n" +
	"\tAPP_CLOSE\x10\x02\x12\x12\n" +
	"\x0eSWITCH_ACCOUNT\x10\x03\"=\n" +
	"\x10HeartbeatRequest\x12)\n" +
	"\x10client_timestamp\x18\x01 \x01(\x03R\x0fclientTimestamp\"i\n" +
	"\x11HeartbeatResponse\x12)\n" +
	"\x10client_timestamp\x18\x01 \x01(\x03R\x0fclientTimestamp\x12)\n" +
	"\x10server_timestamp\x18\x02 \x01(\x03R\x0fserverTimestamp\"\xbc\x01\n" +
	"\x0fBusinessRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12B\n" +
	"\x06params\x18\x02 \x03(\v2*.gatesvr.proto.BusinessRequest.ParamsEntryR\x06params\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\x10BusinessResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"j\n" +
	"\fErrorMessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"-\n" +
	"\tClientAck\x12 \n" +
	"\facked_seq_id\x18\x01 \x01(\x04R\n" +
	"ackedSeqId*\x85\x01\n" +
	"\vRequestType\x12\x13\n" +
	"\x0fREQUEST_UNKNOWN\x10\x00\x12\x11\n" +
	"\rREQUEST_START\x10\x01\x12\x10\n" +
	"\fREQUEST_STOP\x10\x02\x12\x15\n" +
	"\x11REQUEST_HEARTBEAT\x10\x03\x12\x14\n" +
	"\x10REQUEST_BUSINESS\x10\x04\x12\x0f\n" +
	"\vREQUEST_ACK\x10\x05*r\n" +
	"\bPushType\x12\x10\n" +
	"\fPUSH_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fPUSH_START_RESP\x10\x01\x12\x17\n" +
	"\x13PUSH_HEARTBEAT_RESP\x10\x02\x12\x16\n" +
	"\x12PUSH_BUSINESS_DATA\x10\x03\x12\x0e\n" +
	"\n" +
	"PUSH_ERROR\x10\x04B\x0fZ\rgatesvr/protob\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_message_proto_goTypes = []any{
	(RequestType)(0),          // 0: gatesvr.proto.RequestType
	(PushType)(0),             // 1: gatesvr.proto.PushType
	(StopRequest_Reason)(0),   // 2: gatesvr.proto.StopRequest.Reason
	(*ClientRequest)(nil),     // 3: gatesvr.proto.ClientRequest
	(*ServerPush)(nil),        // 4: gatesvr.proto.ServerPush
	(*StartRequest)(nil),      // 5: gatesvr.proto.StartRequest
	(*StartResponse)(nil),     // 6: gatesvr.proto.StartResponse
	(*StopRequest)(nil),       // 7: gatesvr.proto.StopRequest
	(*HeartbeatRequest)(nil),  // 8: gatesvr.proto.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 9: gatesvr.proto.HeartbeatResponse
	(*BusinessRequest)(nil),   // 10: gatesvr.proto.BusinessRequest
	(*BusinessResponse)(nil),  // 11: gatesvr.proto.BusinessResponse
	(*ErrorMessage)(nil),      // 12: gatesvr.proto.ErrorMessage
	(*ClientAck)(nil),         // 13: gatesvr.proto.ClientAck
	nil,                       // 14: gatesvr.proto.ClientRequest.HeadersEntry
	nil,                       // 15: gatesvr.proto.ServerPush.HeadersEntry
	nil,                       // 16: gatesvr.proto.BusinessRequest.ParamsEntry
}
var file_message_proto_depIdxs = []int32{
	0,  // 0: gatesvr.proto.ClientRequest.type:type_name -> gatesvr.proto.RequestType
	14, // 1: gatesvr.proto.ClientRequest.headers:type_name -> gatesvr.proto.ClientRequest.HeadersEntry
	1,  // 2: gatesvr.proto.ServerPush.type:type_name -> gatesvr.proto.PushType
	15, // 3: gatesvr.proto.ServerPush.headers:type_name -> gatesvr.proto.ServerPush.HeadersEntry
	12, // 4: gatesvr.proto.StartResponse.error:type_name -> gatesvr.proto.ErrorMessage
	2,  // 5: gatesvr.proto.StopRequest.reason:type_name -> gatesvr.proto.StopRequest.Reason
	16, // 6: gatesvr.proto.BusinessRequest.params:type_name -> gatesvr.proto.BusinessRequest.ParamsEntry
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
